name: Quartz
on: [push, pull_request]
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          # auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Check environment
        run: |
          echo "hostname:" $(hostname)
          echo "whoami:  " $(whoami)
          echo "date:    " $(date "+%Y-%m-%d %H:%M")
          echo "pwd:     " $(pwd -P)
          # Conda has not been activated- this will change later
          echo "python:  " $(which python)
          echo
          git log -n 1 --date="format:%Y-%m-%d %H:%m" --format=tformat:"%h %cd %an : %s"
          echo
      - name: Set up GitHub PAT
        # Set up PAT for R install_github()
        run: |
          echo "GITHUB_PAT=${{ secrets.GH_PAT_WOZ }}" >> ~/.Renviron
      - name: Run Quartz
        run: |
          tests/test-quartz.sh ${{ matrix.python-version }}
